"""
Scaffolding CLI for mcp-server-kit.

Two subcommands:

    mcp-server-kit add-server <Name>
        In-repo contributor mode. Adds a new server module + test to a *clone*
        of the mcp-server-kit repository and registers it in ``combined.py`` and
        ``__init__.py``. Only valid when run from the repo root.

    mcp-server-kit new <project-dir> [--standalone] [--with-examples ... | --all-examples | --no-examples]
        Standalone project generator for installed users. Emits a brand-new,
        self-contained MCP server project in the current working directory that
        depends on (or vendors) mcp-server-kit.

Author:
    David Gwartney <david.gwartney@gmail.com>
"""

import argparse
import ast
import re
import sys
from pathlib import Path
from typing import Optional

# (prefix, ClassName, import_module) for each server bundled with mcp-server-kit.
BUNDLED_SERVERS = [
    ("greet", "GreetMCPServer", "mcp_server_kit.server"),
    ("contacts", "ContactMCPServer", "mcp_server_kit.contacts"),
    ("wikipedia", "WikipediaMCPServer", "mcp_server_kit.wikipedia"),
    ("weather", "WeatherMCPServer", "mcp_server_kit.weather"),
    ("messaging", "MessagingMCPServer", "mcp_server_kit.messaging"),
]
_BUNDLED_BY_PREFIX = {p: (p, c, m) for p, c, m in BUNDLED_SERVERS}

# Servers that need external-service env vars to actually function.
_ENV_DEPENDENT = {"weather", "messaging"}


def to_snake_case(name: str) -> str:
    """Convert a PascalCase/CamelCase name to snake_case."""
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def to_package_name(project_dir: str) -> str:
    """Derive a valid Python package name from a project directory name.

    ``my-mcp`` -> ``my_mcp``. Leading digits get an underscore prefix.
    """
    base = Path(project_dir).name
    pkg = re.sub(r"[^0-9a-zA-Z_]", "_", base).lower()
    pkg = re.sub(r"_+", "_", pkg).strip("_")
    if not pkg:
        raise ValueError(f"Cannot derive a package name from {project_dir!r}")
    if pkg[0].isdigit():
        pkg = f"_{pkg}"
    return pkg


# --------------------------------------------------------------------------- #
# add-server (in-repo contributor mode) — ported from scripts/new_server.py
# --------------------------------------------------------------------------- #

_TEMPLATE_INTRO = """Copy this file, rename the class and the module, and replace `example_tool`
with your own tool(s). This is the smallest possible AuthenticatedMCPServer
subclass — no external API calls, no SQLite domain tables beyond the
built-in API-key auth store.

See docs/extending.md for the full checklist of what else to update when
adding a new server (combined.py's SERVER_REGISTRY, docs/servers.md, tests)."""


def _find_repo_root() -> Path:
    """Locate the repo root by walking up from CWD looking for the package layout."""
    for candidate in (Path.cwd(), *Path.cwd().parents):
        if (candidate / "mcp_server_kit" / "combined.py").exists() and (
            candidate / "tests"
        ).is_dir():
            return candidate
    raise SystemExit(
        "Error: 'add-server' must be run from a clone of the mcp-server-kit repo "
        "(no mcp_server_kit/combined.py + tests/ found in the current directory or "
        "its parents).\n"
        "If you installed mcp-server-kit and want to start your own project, "
        "use 'mcp-server-kit new <project-dir>' instead."
    )


def _render_repo_module(template: str, name: str, name_snake: str) -> str:
    """Render a new in-repo server module from mcp_server_kit/_template.py."""
    generated_intro = (
        "Generated by 'mcp-server-kit add-server' from mcp_server_kit/_template.py.\n"
        "Replace `example_tool` with your own tool(s) in _register_tools()."
    )
    rendered = template.replace(_TEMPLATE_INTRO, generated_intro)
    rendered = rendered.replace(
        "Minimal starter template for a new MCP server.", f"{name} MCP server."
    )
    rendered = rendered.replace("Template", name)
    rendered = rendered.replace("mcp_server_kit._template", f"mcp_server_kit.{name_snake}")
    return rendered


def _render_repo_test(template: str, name: str, name_snake: str) -> str:
    """Render a new in-repo test module from tests/test__template.py."""
    rendered = template.replace("Template", name)
    rendered = rendered.replace("mcp_server_kit._template", f"mcp_server_kit.{name_snake}")
    rendered = rendered.replace("template_module", f"{name_snake}_module")
    return rendered


def _closing_index(lines: list[str], name: str, closer: str) -> int:
    """
    Index of the line closing the ``name = [...]`` / ``{...}`` literal: the
    first line equal to ``closer`` after the line that assigns ``name``.
    (A fixed look-back window broke once a registry grew past it.)
    """
    start = next(
        (i for i, line in enumerate(lines)
         if line.lstrip().startswith(name) and "=" in line),
        None,
    )
    if start is None:
        raise RuntimeError(f"Could not find {name} in the file being updated")
    for i in range(start + 1, len(lines)):
        if lines[i].strip() == closer:
            return i
    raise RuntimeError(f"Could not find the closing {closer!r} of {name}")


def _update_combined_py(repo_root: Path, name: str, name_snake: str) -> None:
    """Add an import line and a SERVER_REGISTRY entry to combined.py."""
    combined_path = repo_root / "mcp_server_kit" / "combined.py"
    lines = combined_path.read_text().splitlines(keepends=True)

    import_line = f"from mcp_server_kit.{name_snake} import {name}MCPServer\n"
    import_indices = [
        i
        for i, line in enumerate(lines)
        if line.startswith("from mcp_server_kit.") and " import " in line
    ]
    if not import_indices:
        raise RuntimeError("Could not find the mcp_server_kit import block in combined.py")
    insert_at = import_indices[-1] + 1
    for i in import_indices:
        if lines[i] > import_line:
            insert_at = i
            break
    lines.insert(insert_at, import_line)

    registry_entry = f'    ("{name_snake}", {name}MCPServer),\n'
    closing_bracket_idx = _closing_index(lines, "SERVER_REGISTRY", "]")
    lines.insert(closing_bracket_idx, registry_entry)

    combined_path.write_text("".join(lines))
    ast.parse(combined_path.read_text())


def _update_init_py(repo_root: Path, name: str, name_snake: str) -> None:
    """Add the new server class to __init__.py's __all__ and _LAZY_IMPORTS."""
    init_path = repo_root / "mcp_server_kit" / "__init__.py"
    lines = init_path.read_text().splitlines(keepends=True)
    class_name = f"{name}MCPServer"

    all_closing_idx = _closing_index(lines, "__all__", "]")
    lines.insert(all_closing_idx, f'    "{class_name}",\n')

    lazy_closing_idx = _closing_index(lines, "_LAZY_IMPORTS", "}")
    lines.insert(lazy_closing_idx, f'    "{class_name}": "mcp_server_kit.{name_snake}",\n')

    init_path.write_text("".join(lines))
    ast.parse(init_path.read_text())


def add_server(name: str) -> None:
    """Add a new server to a clone of the mcp-server-kit repo (contributor mode)."""
    if not name.isidentifier() or not name[0].isupper():
        raise SystemExit(
            f"Error: '{name}' must be a valid PascalCase identifier (e.g. 'Inventory')."
        )

    repo_root = _find_repo_root()
    package_dir = repo_root / "mcp_server_kit"
    tests_dir = repo_root / "tests"
    name_snake = to_snake_case(name)
    module_path = package_dir / f"{name_snake}.py"
    test_path = tests_dir / f"test_{name_snake}.py"

    for path in (module_path, test_path):
        if path.exists():
            raise SystemExit(f"Error: {path} already exists — refusing to overwrite.")

    module_template = (package_dir / "_template.py").read_text()
    test_template = (tests_dir / "test__template.py").read_text()

    module_path.write_text(_render_repo_module(module_template, name, name_snake))
    test_path.write_text(_render_repo_test(test_template, name, name_snake))
    _update_combined_py(repo_root, name, name_snake)
    _update_init_py(repo_root, name, name_snake)

    print(f"Created {module_path.relative_to(repo_root)}")
    print(f"Created {test_path.relative_to(repo_root)}")
    print(f"Updated mcp_server_kit/combined.py (added {name}MCPServer to SERVER_REGISTRY)")
    print(f"Updated mcp_server_kit/__init__.py (added {name}MCPServer to __all__/_LAZY_IMPORTS)")
    print()
    print("Remaining steps (see docs/extending.md):")
    print(f"  1. Implement your tools in {module_path.relative_to(repo_root)}'s _register_tools()")
    print("  2. Add a section for it in docs/servers.md")
    print(f"  3. Fill in {test_path.relative_to(repo_root)} with real test cases")
    print("  4. Run: uv run pytest")
    print("  5. Start the combined server and curl the new endpoint:")
    print("     uv run -m mcp_server_kit.combined --port 8000")
    print(f"     curl -X POST http://localhost:8000/{name_snake}/mcp ...")


# --------------------------------------------------------------------------- #
# new (standalone project generator for installed users)
# --------------------------------------------------------------------------- #


def _resolve_examples(args) -> list:
    """Determine which bundled servers to include, from flags or an interactive prompt."""
    if args.no_examples:
        return []
    if args.all_examples:
        return [p for p, _, _ in BUNDLED_SERVERS]
    if args.with_examples:
        chosen = [s.strip() for s in args.with_examples.split(",") if s.strip()]
        unknown = [c for c in chosen if c not in _BUNDLED_BY_PREFIX]
        if unknown:
            raise SystemExit(
                f"Error: unknown bundled server(s): {', '.join(unknown)}. "
                f"Choose from: {', '.join(p for p, _, _ in BUNDLED_SERVERS)}"
            )
        return chosen
    # No flag given: prompt interactively if we have a TTY, else default to none.
    if not sys.stdin.isatty():
        return []
    print("Which bundled example servers should be included? (y/N for each)")
    chosen = []
    for prefix, _cls, _mod in BUNDLED_SERVERS:
        note = " (needs API-key env vars)" if prefix in _ENV_DEPENDENT else ""
        answer = input(f"  include '{prefix}'{note}? [y/N] ").strip().lower()
        if answer in ("y", "yes"):
            chosen.append(prefix)
    return chosen


def _my_server_py(pkg: str, standalone: bool) -> str:
    base_import = (
        f"from {pkg}._base.base import AuthenticatedMCPServer, lazy_module_instances"
        if standalone
        else "from mcp_server_kit.base import AuthenticatedMCPServer, lazy_module_instances"
    )
    return f'''"""Your MCP server. Add tools inside ``_register_tools()``."""

{base_import}


class MyServer(AuthenticatedMCPServer):
    """A starter server with a single example tool."""

    def _register_tools(self) -> None:
        @self.mcp.tool(description="Add two numbers")
        def add(a: int, b: int) -> int:
            """Return the sum of two integers."""
            return a + b


# Lazy module-level ``server`` / ``mcp`` — built on first access, not on import.
__getattr__ = lazy_module_instances(MyServer)

if __name__ == "__main__":
    MyServer().main()
'''


def _combined_py(pkg: str, examples: list) -> str:
    imports = [f"from {pkg}.my_server import MyServer"]
    registry = ['    ("my_server", MyServer),']
    for prefix in examples:
        _p, cls, mod = _BUNDLED_BY_PREFIX[prefix]
        imports.append(f"from {mod} import {cls}")
        registry.append(f'    ("{prefix}", {cls}),')
    imports_block = "\n".join(imports)
    registry_block = "\n".join(registry)
    return f'''"""Combined ASGI app mounting every server in SERVER_REGISTRY at its own path."""

import argparse
from contextlib import AsyncExitStack, asynccontextmanager

import uvicorn
from starlette.applications import Starlette
from starlette.routing import Mount

{imports_block}

# To add a server: append (url_prefix, ServerClass) here.
SERVER_REGISTRY = [
{registry_block}
]


def _build():
    routes, sub_apps, servers = [], [], []
    for prefix, ServerClass in SERVER_REGISTRY:
        srv = ServerClass()
        sub_app = srv.mcp.http_app(
            path="/mcp",
            middleware=srv._http_middleware,
            transport="streamable-http",
        )
        routes.append(Mount(f"/{{prefix}}", app=sub_app))
        sub_apps.append(sub_app)
        servers.append(srv)
    return routes, sub_apps, servers


def build_app() -> Starlette:
    routes, sub_apps, servers = _build()

    @asynccontextmanager
    async def _lifespan(parent_app):
        # Starlette's Mount does not propagate sub-app lifespans automatically;
        # compose them here so each server's background workers start and stop
        # correctly.
        try:
            async with AsyncExitStack() as stack:
                for sub_app in sub_apps:
                    await stack.enter_async_context(sub_app.lifespan(sub_app))
                yield
        finally:
            for srv in servers:
                srv.close()

    return Starlette(lifespan=_lifespan, routes=routes)


_app_cache = {{}}


def __getattr__(name):
    if name == "app":
        if "app" not in _app_cache:
            _app_cache["app"] = build_app()
        return _app_cache["app"]
    raise AttributeError(f"module {{__name__!r}} has no attribute {{name!r}}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Combined MCP Server")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()
    uvicorn.run("{pkg}.combined:app", host=args.host, port=args.port)
'''


def _test_my_server_py(pkg: str) -> str:
    return f'''"""Tests for the generated MyServer.

Uses fastmcp's public in-memory ``Client`` (stable across fastmcp versions)
rather than private internals.
"""

import asyncio

from fastmcp import Client

from {pkg}.my_server import MyServer


def test_add_tool_registered_and_works(tmp_path):
    srv = MyServer(db_path=str(tmp_path / "keys.db"))

    async def _check():
        async with Client(srv.mcp) as client:
            tools = {{t.name for t in await client.list_tools()}}
            assert "add" in tools
            result = await client.call_tool("add", {{"a": 2, "b": 3}})
            assert result.data == 5

    asyncio.run(_check())


def test_import_creates_no_db(tmp_path, monkeypatch):
    """Importing the server module must not create a database on disk."""
    monkeypatch.chdir(tmp_path)
    import importlib

    import {pkg}.my_server as m

    importlib.reload(m)
    assert not list(tmp_path.glob("*.db"))
'''


def _pyproject(project_name: str, pkg: str, standalone: bool, needs_kit: bool) -> str:
    deps = []
    if standalone:
        deps += [
            '    "fastmcp>=2.14.5",',
            '    "httpx>=0.27.0",',
            '    "starlette>=0.37.0",',
            '    "uvicorn>=0.30.0",',
        ]
    if not standalone or needs_kit:
        deps.append('    "mcp-server-kit>=0.1.0",')
    deps_block = "\n".join(deps)
    return f'''[project]
name = "{project_name}"
version = "0.1.0"
description = "An MCP server generated with mcp-server-kit."
requires-python = ">=3.10"
dependencies = [
{deps_block}
]

[project.optional-dependencies]
test = [
    "pytest>=8.0.0",
    "httpx>=0.27.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["{pkg}"]
'''


def _readme(project_name: str, pkg: str, standalone: bool, examples: list, needs_kit: bool) -> str:
    lines = [
        f"# {project_name}",
        "",
        "An MCP server generated with [mcp-server-kit](https://pypi.org/project/mcp-server-kit/).",
        "",
        "## Install & run",
        "",
        "This project uses [uv](https://github.com/astral-sh/uv) — not pip.",
        "",
        "```bash",
        "uv sync",
        f"uv run python -m {pkg}.combined --port 8000   # serves /my_server/mcp",
        "```",
        "",
        "The combined server prints a generated API key on first run (via logging). ",
        "Send it as the `X-API-Key` header when calling tools.",
        "",
        "## Add tools",
        "",
        f"Edit `{pkg}/my_server.py` and add tools inside `_register_tools()`.",
        "",
    ]
    if standalone and needs_kit:
        lines += [
            "> **Note:** you selected `--standalone` but also included bundled example ",
            "> servers, which are imported from the `mcp-server-kit` package. As a result ",
            "> `mcp-server-kit` remains a dependency of this project. Remove the bundled ",
            "> servers from `combined.py` (and the dependency from `pyproject.toml`) for a ",
            "> fully dependency-free project.",
            "",
        ]
    env_needed = [e for e in examples if e in _ENV_DEPENDENT]
    if env_needed:
        lines += [
            f"> **Note:** the bundled `{', '.join(env_needed)}` server(s) require API-key ",
            "> environment variables to function (e.g. `OPENWEATHER_API_KEY`, "
            "`TWILIO_ACCOUNT_SID`).",
            "",
        ]
    return "\n".join(lines)


def _vendor_base(project_path: Path, pkg: str) -> None:
    """Copy base.py/middleware.py/database.py into <pkg>/_base/ with rewritten imports."""
    import mcp_server_kit

    src_dir = Path(mcp_server_kit.__file__).parent
    base_dir = project_path / pkg / "_base"
    base_dir.mkdir(parents=True, exist_ok=True)
    (base_dir / "__init__.py").write_text('"""Vendored mcp-server-kit base classes."""\n')
    for fname in ("database.py", "middleware.py", "base.py"):
        text = (src_dir / fname).read_text()
        text = text.replace(
            "from mcp_server_kit.database import", f"from {pkg}._base.database import"
        )
        text = text.replace(
            "from mcp_server_kit.middleware import", f"from {pkg}._base.middleware import"
        )
        (base_dir / fname).write_text(text)


def new_project(
    project_dir: str,
    standalone: bool,
    examples: list,
) -> Path:
    """Generate a standalone MCP server project directory. Returns its path."""
    project_path = Path(project_dir)
    if project_path.exists() and any(project_path.iterdir()):
        raise SystemExit(f"Error: {project_path} already exists and is not empty.")

    pkg = to_package_name(project_dir)
    project_name = project_path.name
    needs_kit = bool(examples)  # bundled servers import from mcp_server_kit

    (project_path / pkg).mkdir(parents=True, exist_ok=True)
    (project_path / "tests").mkdir(parents=True, exist_ok=True)

    (project_path / pkg / "__init__.py").write_text('__version__ = "0.1.0"\n')
    (project_path / pkg / "my_server.py").write_text(_my_server_py(pkg, standalone))
    (project_path / pkg / "combined.py").write_text(_combined_py(pkg, examples))
    (project_path / "tests" / "__init__.py").write_text("")
    (project_path / "tests" / "test_my_server.py").write_text(_test_my_server_py(pkg))
    (project_path / "pyproject.toml").write_text(
        _pyproject(project_name, pkg, standalone, needs_kit)
    )
    (project_path / "README.md").write_text(
        _readme(project_name, pkg, standalone, examples, needs_kit)
    )
    if standalone:
        _vendor_base(project_path, pkg)

    print(f"Created project {project_path}/ (package '{pkg}')")
    if examples:
        print(f"  bundled servers: {', '.join(examples)}")
    print(f"  mode: {'standalone (vendored base)' if standalone else 'depends on mcp-server-kit'}")
    if standalone and needs_kit:
        print("  note: bundled servers keep mcp-server-kit as a dependency (see README).")
    print()
    print("Next steps:")
    print(f"  cd {project_path} && uv sync --extra test")
    print(f"  uv run python -m {pkg}.combined --port 8000")
    return project_path


# --------------------------------------------------------------------------- #
# CLI entry point
# --------------------------------------------------------------------------- #


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="mcp-server-kit",
        description="Scaffold MCP servers with mcp-server-kit.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_add = sub.add_parser(
        "add-server",
        help="Add a server to a clone of the mcp-server-kit repo (contributor mode).",
    )
    p_add.add_argument("name", help="PascalCase server name, e.g. 'Inventory'.")

    p_new = sub.add_parser(
        "new",
        help="Generate a new standalone MCP server project.",
    )
    p_new.add_argument("project_dir", help="Directory to create for the new project.")
    p_new.add_argument(
        "--standalone",
        "--vendor",
        dest="standalone",
        action="store_true",
        help="Vendor the base classes instead of depending on mcp-server-kit.",
    )
    ex = p_new.add_mutually_exclusive_group()
    ex.add_argument(
        "--with-examples",
        help="Comma-separated bundled servers to include (e.g. 'greet,weather').",
    )
    ex.add_argument(
        "--all-examples", action="store_true", help="Include all bundled servers."
    )
    ex.add_argument(
        "--no-examples", action="store_true", help="Include no bundled servers."
    )
    return parser


def main(argv: Optional[list] = None) -> None:
    args = build_parser().parse_args(argv)
    if args.command == "add-server":
        add_server(args.name)
    elif args.command == "new":
        examples = _resolve_examples(args)
        new_project(args.project_dir, args.standalone, examples)


if __name__ == "__main__":
    main()
