#!/usr/bin/env python3
"""
Scaffold a new MCP server from mcp_examples/_template.py.

Usage:
    uv run python scripts/new_server.py <Name>

Example:
    uv run python scripts/new_server.py Inventory

Generates:
    mcp_examples/<name_snake>.py   — new server module (class <Name>MCPServer)
    tests/test_<name_snake>.py     — matching test skeleton

And updates:
    mcp_examples/combined.py       — adds an import + SERVER_REGISTRY entry
    mcp_examples/__init__.py       — adds to __all__ and _LAZY_IMPORTS

Refuses to overwrite existing files. Does not touch docs/servers.md or run
tests for you — see the printed checklist at the end for remaining steps.

Author:
    David Gwartney <david.gwartney@gmail.com>
"""

import ast
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGE_DIR = REPO_ROOT / "mcp_examples"
TESTS_DIR = REPO_ROOT / "tests"


def to_snake_case(name: str) -> str:
    """Convert a PascalCase/CamelCase name to snake_case."""
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


_TEMPLATE_INTRO = """Copy this file, rename the class and the module, and replace `example_tool`
with your own tool(s). This is the smallest possible AuthenticatedMCPServer
subclass — no external API calls, no SQLite domain tables beyond the
built-in API-key auth store.

See docs/extending.md for the full checklist of what else to update when
adding a new server (combined.py's SERVER_REGISTRY, docs/servers.md, tests)."""


def render_module(name: str, name_snake: str) -> str:
    """Render a new server module from mcp_examples/_template.py."""
    template = (PACKAGE_DIR / "_template.py").read_text()
    generated_intro = (
        "Generated by scripts/new_server.py from mcp_examples/_template.py.\n"
        "Replace `example_tool` with your own tool(s) in _register_tools()."
    )
    rendered = template.replace(_TEMPLATE_INTRO, generated_intro)
    rendered = rendered.replace(
        "Minimal starter template for a new MCP server.", f"{name} MCP server."
    )
    # Substitute the class/module name last so the generated_intro's own
    # literal "_template.py" reference (to the source file) survives intact.
    rendered = rendered.replace("Template", name)
    rendered = rendered.replace("mcp_examples._template", f"mcp_examples.{name_snake}")
    return rendered


def render_test(name: str, name_snake: str) -> str:
    """Render a new test module from tests/test__template.py."""
    template = (TESTS_DIR / "test__template.py").read_text()
    rendered = template.replace("Template", name)
    rendered = rendered.replace("mcp_examples._template", f"mcp_examples.{name_snake}")
    rendered = rendered.replace("template_module", f"{name_snake}_module")
    return rendered


def update_combined_py(name: str, name_snake: str) -> None:
    """Add an import line and a SERVER_REGISTRY entry to combined.py."""
    combined_path = PACKAGE_DIR / "combined.py"
    lines = combined_path.read_text().splitlines(keepends=True)

    import_line = f"from mcp_examples.{name_snake} import {name}MCPServer\n"
    import_indices = [
        i for i, line in enumerate(lines)
        if line.startswith("from mcp_examples.") and " import " in line
    ]
    if not import_indices:
        raise RuntimeError("Could not find the mcp_examples import block in combined.py")
    insert_at = import_indices[-1] + 1
    for i in import_indices:
        if lines[i] > import_line:
            insert_at = i
            break
    lines.insert(insert_at, import_line)

    registry_entry = f'    ("{name_snake}", {name}MCPServer),\n'
    closing_bracket_idx = next(
        i for i, line in enumerate(lines)
        if line.strip() == "]" and any(
            "SERVER_REGISTRY" in lines[j] for j in range(max(0, i - 10), i)
        )
    )
    lines.insert(closing_bracket_idx, registry_entry)

    combined_path.write_text("".join(lines))
    ast.parse(combined_path.read_text())


def update_init_py(name: str, name_snake: str) -> None:
    """Add the new server class to __init__.py's __all__ and _LAZY_IMPORTS."""
    init_path = PACKAGE_DIR / "__init__.py"
    lines = init_path.read_text().splitlines(keepends=True)
    class_name = f"{name}MCPServer"

    all_closing_idx = next(
        i for i, line in enumerate(lines)
        if line.strip() == "]" and any(
            "__all__" in lines[j] for j in range(max(0, i - 20), i)
        )
    )
    lines.insert(all_closing_idx, f'    "{class_name}",\n')

    lazy_closing_idx = next(
        i for i, line in enumerate(lines)
        if line.strip() == "}" and any(
            "_LAZY_IMPORTS" in lines[j] for j in range(max(0, i - 20), i)
        )
    )
    lines.insert(lazy_closing_idx, f'    "{class_name}": "mcp_examples.{name_snake}",\n')

    init_path.write_text("".join(lines))
    ast.parse(init_path.read_text())


def main() -> None:
    if len(sys.argv) != 2:
        print(f"Usage: uv run python {Path(__file__).name} <Name>", file=sys.stderr)
        sys.exit(1)

    name = sys.argv[1]
    if not name.isidentifier() or not name[0].isupper():
        print(
            f"Error: '{name}' must be a valid PascalCase identifier (e.g. 'Inventory').",
            file=sys.stderr,
        )
        sys.exit(1)

    name_snake = to_snake_case(name)
    module_path = PACKAGE_DIR / f"{name_snake}.py"
    test_path = TESTS_DIR / f"test_{name_snake}.py"

    for path in (module_path, test_path):
        if path.exists():
            print(f"Error: {path} already exists — refusing to overwrite.", file=sys.stderr)
            sys.exit(1)

    module_path.write_text(render_module(name, name_snake))
    test_path.write_text(render_test(name, name_snake))
    update_combined_py(name, name_snake)
    update_init_py(name, name_snake)

    print(f"Created {module_path.relative_to(REPO_ROOT)}")
    print(f"Created {test_path.relative_to(REPO_ROOT)}")
    print(f"Updated mcp_examples/combined.py (added {name}MCPServer to SERVER_REGISTRY)")
    print(f"Updated mcp_examples/__init__.py (added {name}MCPServer to __all__/_LAZY_IMPORTS)")
    print()
    print("Remaining steps (see docs/extending.md):")
    print(f"  1. Implement your tools in {module_path.relative_to(REPO_ROOT)}'s _register_tools()")
    print(f"  2. Add a section for it in docs/servers.md")
    print(f"  3. Fill in {test_path.relative_to(REPO_ROOT)} with real test cases")
    print(f"  4. Run: uv run pytest")
    print(f"  5. Start the combined server and curl the new endpoint:")
    print(f"     uv run -m mcp_examples.combined --port 8000")
    print(f"     curl -X POST http://localhost:8000/{name_snake}/mcp ...")
    print(f"  6. Register it as a new MCP Tool in Kore AI (Test → Import)")


if __name__ == "__main__":
    main()
